# Generated by Django 4.1.6 on 2023-02-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_companyrepresentative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='dimensions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='dimensions',
            field=models.TextField(blank=True),
        ),
    ]
