# Generated by Django 4.1.6 on 2023-02-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_image_alter_companymodel_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='dimensions',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='companymodel',
            name='images',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='images',
        ),
        migrations.AddField(
            model_name='companymodel',
            name='images',
            field=models.ManyToManyField(blank=True, to='polls.image'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='images',
            field=models.ManyToManyField(blank=True, to='polls.image'),
        ),
    ]
