# Generated by Django 4.1.6 on 2023-02-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_image_alter_companymodel_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='dimensions',
            field=models.TextField(blank=True),
        ),
    ]
