# Generated by Django 4.1.6 on 2023-03-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_companymodel_dimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymodel',
            name='images',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='images',
        ),
        migrations.AddField(
            model_name='companymodel',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
